### ISSUE TITLE
How do clients proactively query for certificates

### ISSUE THREAD

**Issue by ekinnear** [egorbaty/draft-httpbis-secondary-server-certs#23]
The following paragraph refers to querying for a certificate on a subsequent connection: 

> As noted in the Security Considerations of {{EXPORTED-AUTH}}, it is difficult to
formally prove that an endpoint is jointly authoritative over multiple
certificates, rather than individually authoritative on each certificate. As a
result, clients MUST NOT assume that because one origin was previously
colocated with another, those origins will be reachable via the same endpoints
in the future. Clients MUST NOT consider previous secondary certificates to be
validated after TLS session resumption. However, clients MAY proactively query
for previously-presented secondary certificates.

Have we explicitly defined what this query looks like?

**Comment by egorbaty** [comment]
Ah, this is a holdover from the previous draft. I'm not totally sure what the answer to this (and TLS session resumption), is right now.

**Comment by egorbaty** [comment]
Following up: Ilari Liusvaara mentioned that it should be possible to include authenticator requests (as far as the exported authenticator spec is concerned) in the same frame type. Not sure that we would actually need to reuse a frame; we could add a server authenticator request frame as well. That might help handling TLS session resumption, as well as some of the Altsvc authentication querying concerns that were raised there.
